#!/bin/sh
wget https://github.com/DukeCheng/ConfigTransform/releases/download/v0.1/ConfigTransform.zip -O /tmp/ConfigTransform.zip 
unzip ConfigTransform.zip -d ConfigTransform
mkdir /usr/lib/dktools
cp ConfigTransform/* /usr/lib/dktools/
cp ConfigTransform/configtransform /usr/bin/
chmod 700 /usr/bin/configtransform
echo "configtransform install successful"

