#!/bin/sh
wget https://github.com/DukeCheng/ConfigTransform/releases/download/v0.1/configtransform.zip -O /tmp/configtransform.zip 
unzip configtransform.zip -d configtransform
mkdir /usr/lib/dktools
cp configtransform/* /usr/lib/dktools/
cp configtransform/configtransform /usr/bin/
chmod 700 /usr/bin/configtransform
echo "configtransform install successful"

