#!/bin/sh
wget https://github.com/DukeCheng/ConfigTransform/releases/download/v0.1/ConfigTransform.zip -O /tmp/ConfigTransform.zip 
unzip /tmp/ConfigTransform.zip -d /tmp/ConfigTransform
mkdir /usr/lib/dktools

rm -rf /usr/bin/configtransform
rm -rf /usr/lib/dktools/ConfigTransform*

cp /tmp/ConfigTransform/* /usr/lib/dktools/
cp /tmp/ConfigTransform/configtransform /usr/bin/
chmod 700 /usr/bin/configtransform
rm -rf /tmp/ConfigTransform*
echo "configtransform install successful"

